Add Edge support to webpush
jazzband/django-push-notifications pull request #631
Opened 2021-11-12 10:25 UTC by simonkern

This adds Edge support to webpush and showcases an easier way to extract browsername and version for Chrome, Edge, and Opera in the README.

Any feedback would be greatly appreciated.

2021-11-12 14:08 UTC, auvipy approved these changes

2021-11-14 18:35 UTC, Andrew-Chen-Wang commented
@simonkern I don't know if this statement is correct, but the edge url seems to change all the time? Is it possible to make this an EDGE setting?

2021-11-16 15:14 UTC, Andrew-Chen-Wang requested changes

2021-11-16 15:14 UTC, Andrew-Chen-Wang commented on push_notifications/models.py
> +		help_text=_("Currently only support to Chrome, Firefox, Edge and Opera browsers")
Please create a migration!

2021-11-17 14:57 UTC, simonkern commented
> @simonkern I don't know if this statement is correct, but the edge url seems to change all the time? Is it possible to make this an EDGE setting?

I was not able to produce an URL with another domain so far. However, I was also unable to find proper documentation on this matter. But if this URL would change all the time, it would be necessary to adapt the model to store the baseURL as well, imho. What do you think and suggest?

2021-11-17 15:10 UTC, Andrew-Chen-Wang commented
I'm not sure what you mean by adapt the model to store the URL. I was suggesting in settings.py, instead of hard coding the url, allow for user customization like the chrome url. Additionally, make sure to create a migration!

2021-11-17 15:24 UTC, simonkern commented
Doesn't WP_POST_URL already solve this?

2021-11-17 15:30 UTC, Andrew-Chen-Wang approved these changes
ah gotcha sorry 😅 LGTM then

2021-11-17 15:30 UTC, Andrew-Chen-Wang commented
AHH but wait migration file!

2021-11-17 17:30 UTC, merged

2021-11-17 17:31 UTC, Andrew-Chen-Wang commented
Thanks again!