Add db_index=True for registration_id on APNSDevice model
jazzband/django-push-notifications pull request #747
Opened 2024-12-20 12:31 UTC by mikaelengstrom

When having huge list apns devices without the unique setting activated (UNIQUE_REG_ID) updating devices via the drf-endpoint becomes very slow. Adding an index resolves that.

For reference our current prod-environment have select-statements to this fields taking up to 9 seconds

2024-12-30 23:51 UTC, 50-Course approved these changes

2024-12-30 23:51 UTC, 50-Course commented on push_notifications/models.py
> +		unique=SETTINGS["UNIQUE_REG_ID"],
Nice catch @mikaelengstrom! This looks great, one more thing, i would like to a profiling request (to have closer look) for this after the holidays before merging. 

For now, approving this PR. thanks.

2025-01-05 17:12 UTC, 50-Course requested changes

2025-01-05 17:12 UTC, 50-Course commented on push_notifications/models.py
> +		unique=SETTINGS["UNIQUE_REG_ID"],
one more thing @mikaelengstrom before we call this merged, 

here we seem to be resolving `unique=False` given the constant, `UNIQUE_REG_ID` defaults to false. is this intentional? 

happy new year

2025-01-05 22:18 UTC, mikaelengstrom commented on push_notifications/models.py
> +		unique=SETTINGS["UNIQUE_REG_ID"],
@50-Course Yes. So before this change, the unique attribute is set based on the UNIQUE_REG_ID boolean setting, which is implicitly creating an index. However, for those of running the default value for `UNIQUE_REG_ID` (False), no index is created making it very inperformant.

So in essence, after this change, either the `db_index` or the `unique` attribute will be set depending on the users settings. Ensuring that some kind of index is created.

2025-01-05 23:43 UTC, 50-Course commented on push_notifications/models.py
> +		unique=SETTINGS["UNIQUE_REG_ID"],
right got it, thanks!

2025-01-05 23:44 UTC, 50-Course approved these changes

2025-01-05 23:44 UTC, merged